### ISSUE TITLE
addOrUpdateContact.php

### ISSUE THREAD

**Issue by LeachCreative** [constantcontact/php-sdk#107]
I'm attempting to use the addOrUpdateContact example you guy have, and it is throwing a catchable error:

Catchable fatal error: Argument 1 passed to Ctct\Components\Contacts\Contact::create() must be of the type array, object given, called in /home/saveinju/public_html/wp-content/themes/childress-new/functions.php on line 642 and defined in /home/saveinju/public_html/wp-content/themes/childress-new/vendor/constantcontact/constantcontact/src/Ctct/Components/Contacts/Contact.php on line 147

It works fine when I try add a new user, but when one already exists, it starts throwing errors like the one above.  Any ideas?

**Comment by WoogieNoogie** [comment]
Sorry about this, looks like not only a bug in the example code, but also a bug within the updateContact method. I've updated the corresponding code in PR #106 , so we'll have this fixed in version 2.1, but you can see what changes needed to be made to the example code in that PR.

I know it's a bit of an inconvenience, but we appreciate you finding and reporting this!

**Comment by WoogieNoogie** [comment]
Fixed in version 2.1.0
