### ISSUE TITLE
Resubscribe contact with OPTOUT status

### ISSUE THREAD

**Issue by raul-dan** [constantcontact/php-sdk#136]
We have some users that unsubscribed from receiving our newsletters but they changed their mind a couple of months after.

They currently have the status "OPTOUT" and whenever our application tries to subscribe them via API we get a Bad Request response code.

What is the correct process to resubscribe a previously unsubscribed user?

**Comment by WoogieNoogie** [comment]
Would you be able to provide a bit more information about the action you're taking, and the response you're receiving? For example, if you're trying to create a contact in this case, it would return with a bad response because you would need to update the existing contact to convert it back into active status. On the other hand, if you're already doing this, the bad response may be due to the action being flagged as an action by the account owner, and not the contact.

**Comment by raul-dan** [comment]
@WoogieNoogie I'm doing it via the API, so I guess its an action by the account owner. 

This is the subscribe method:

``` php
        public function subscribe($email, $params = [])
        {
            $contacts = $this->client->contactService->getContacts(self::TOKEN, [
                'email' => $email
            ]);

            if(!count($contacts->results)) {
                $data = [
                    'email_addresses' => [
                        ["email_address" => $email]
                    ],
                    'lists' => [
                        [ 'id' => (string) self::DEFAULT_LIST ]
                    ],
                    'status' => 'ACTIVE',
                    'source' => 'API'
                ];

                $contact = Contact::create($data);

                $response = $this->client->contactService->addContact(self::TOKEN, $contact);
            } else {
                $contact = $contacts->results[0];

                if($contact->status != 'ACTIVE') {
                    $contact->status = 'ACTIVE';
                    $list = new ContactList();
                    $list->id = (string) self::DEFAULT_LIST;
                    $contact->addList($list);

                    $result = $this->client->contactService->updateContact(self::TOKEN, $contact);
                }
            }
        }
```

Do you suggest to approach another method to re-subscribe existing contacts?

**Comment by handoyo** [comment]
Hi @lrauldan,

Have you succeed in re-subscribe existing contacts?

**Comment by raul-dan** [comment]
@handoyo, no, I can still see "Bad Request" errors in our logs.

**Comment by handoyo** [comment]
@lrauldan Please try to add these parameters in your updateContact function. 

`{
  "email_addresses": [
    {
            "email_address": "xxxx@xxx.com",
            "opt_in_source" : "ACTION_BY_VISITOR"
    }
    ],
    "lists" : [
        {
            "id" : "xxxxx"
        }
        ]
}`

And don't forget to pass the contactID to in your header. I'm using v1.x lib so my code may differs than yours. And that's why I didn't include my code here. Let me know if it works for you. :)

**Comment by raul-dan** [comment]
@handoyo, I was able to resubscribe a contact by adding the parameter 'action_by' => 'ACTION_BY_VISITOR'. If anyone has the same issue as I did, the following code block should do the trick:

```php
if($contact->status != 'ACTIVE') {
	$contact->status = 'ACTIVE';
	$list = new ContactList();
	$list->id = (string) self::DEFAULT_LIST;
	$contact->addList($list);
	$contact->email_addresses[0]->status = 'ACTIVE';

	$result = $this->client->contactService->updateContact(self::TOKEN, $contact, [
		'action_by' => 'ACTION_BY_VISITOR'
	]);
}
```
