### ISSUE TITLE
Inconsistencies in example code 

### ISSUE THREAD

**Issue by WhereBeTheDan** [constantcontact/php-sdk#137]
The current stable release includes example code in addOrUpdateContact.php that states:

> The third parameter of addContact defaults to false, but if this were set to true it would tell Constant Contact that this action is being performed by the contact themselves, and gives the ability to opt contacts back in and trigger Welcome/Change-of-interest emails.

However, it looks like that version of the function is not in stable and only exists in the dev branch. The third parameter of addContact in stable still requires an array of parameters.

**Comment by WoogieNoogie** [comment]
Good catch, that comment is incorrect. However, the behavior of the method is still the same - if the third parameter is left out, it will still default to taking action as the account owner, and not the contact itself. Definitely something we'll want to clean up, but probably not as pressing of a change since the sample code works as intended.

**Comment by WhereBeTheDan** [comment]
Right, I was looking for the non default behavior, but I believe by passing `[ 'action_by' => 'ACTION_BY_VISITOR' ]` as the 3rd parameter you can achieve the same result. Just wanted to post in case someone else encountered the same issue.
