### ISSUE TITLE
Fatal error on ContactService->getContacts() when request throws an error

### ISSUE THREAD

**Issue by zackkatz** [constantcontact/php-sdk#66]
Last night, when the Mashery API was down, the result of the `getContacts` REST request was an error.

The `ContactService->getContacts()` method decodes the JSON and assumes a successful request and that `$body['results']` and `$body['meta']` exist. This results in a fatal error instead of an exception.

See here for what I mean:
https://github.com/constantcontact/php-sdk/blob/development/src/Ctct/Services/ContactService.php#L29-L34

This is also an issue for other services, such as the Email Marketing Service: https://github.com/constantcontact/php-sdk/blob/development/src/Ctct/Services/EmailMarketingService.php#L41-L46

There should be better handling when the JSON response is an error.

**Comment by WoogieNoogie** [comment]
I've done some work with [Guzzle](http://docs.guzzlephp.org/en/latest/) to move our current back end over to them, and I believe this will solve the issue of these unexpected exceptions. Any non-okay status code will throw a CtctException with how my current implementation is set up.

We're looking at releasing this as a version 2.0.0 in the near future - only caveat is we're also looking to drop support for PHP 5.3 - mainly since this is a requirement for the newest version of Guzzle.

**Comment by zackkatz** [comment]
@WoogieNoogie This would be *very* bad for me; WordPress only requires 5.2. 5.3 was a big problem for users to upgrade their servers to. 5.4+ would be very bad again. I would not like this at all.

**Comment by WoogieNoogie** [comment]
Sorry, I didn't mean to make it sound like we were going to drop support of 5.3 altogether. We're going to set up a strategy that allows for fixes to the 1.x versions for anything critical or breaking, and continue to make those versions available for anyone running on that version of PHP.

Earlier I mentioned that the root cause of this issue was a catastrophic failure on our back end services, and our operations teams are working to ensure this doesn't happen in the future. Since there's not a code change to capture this, I wanted to make sure we did mention that in these extremely rare, unforeseeable circumstances, we would have an incoming fix in the code as a last line of defense, the work just ended up falling into our 5.4 work.

Does this help put you a bit more at ease about this? We're up to an extended conversation about this if you still have concerns or questions. I don't want to close the book on this if there are any stones left to be turned. Feel free to reply here, or email us at webservices@constantcontact.com
