### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by eod696** [constantcontact/php-sdk#91]
Why is this api so complicated?  Is it necessary for devs to be able to manipulate your entire data model from a remote website?  Why has it changed so drastically form version one to version two?  Why does it say in the Contact object that the RENAMED property of email_addresses from emailAddress should be an array, and the API gives me this error [ #/email_addresses/0: Value is of a disallowed type. Allowed types are: Object. ] when I submit an add request?

**Comment by egaiter** [comment]
Hello,

One of our major goals with our APIs was to provide a comprehensive interface to our most heavily used products in order to allow for powerful integrations that can range from very simple to very complex. Many of the changes from V1 to V2 were designed to make things like parsing API responses easier, as libraries to automatically parse JSON as an object are often easily available.

In regards to the error that you are seeing from the API, that is going to be because the data that is sent is not following the data model described here: http://developer.constantcontact.com/docs/contacts-api/contacts-resource.html

Here is a very simple code sample that demonstrates the structure of an email address for a contact in PHP:
```
    $contact = new stdClass();
    $emailAddress = new stdClass();
    $emailAddress->email_address = "email@example.com";
    $contact->email_addresses = Array($emailAddress);
```
Additionally, you could do the same thing with our PHP SDK using this code:
```
    $contact = new Contact();
    $contact->addEmail(EmailAddress::create(Array("email_address" => "email@example.com")));
```
Hopefully this should give you some steps towards resolving the error that you ran into. If you have any general usage questions about our API or SDKs, you can reach our API support group directly at webservices@constantcontact.com

Elijah Gaiter
Constant Contact

**Comment by zanematthew** [comment]
I too have been using this API, but have had different experiences. My experience has been positive, I find GitHub is active, and the API is easy to follow.

However I do sense your frustration (we have all been there), what other questions do you have?
