### ISSUE TITLE
Support to tags

### ISSUE THREAD

**Issue by wisquimas** [constantcontact/php-sdk#93]
You don´t have support to tags?

**Comment by egaiter** [comment]
Hello,

Currently the SDK and the API do not have support for Tags. We do have future plans for our API that will enable the use of Tags, but I do not currently have any timeline that I can provide for that. You can read more about the current differences between API functionality and UI functionality here: http://developer.constantcontact.com/docs/contacts-api/api-gui-func.html

Elijah Gaiter
API Support Engineer
Constant Contact

**Comment by RogFed** [comment]
Hey, 

So if I need to filter contacts say by Male or Female using the API, what would you recommend? Tags seemed like the way to go.

**Comment by egaiter** [comment]
With the current tools available in the API I would personally suggest creating unique lists that could be used for this purpose. Since we allow up to 1,000 lists in an account at any time, this should not present any complications with things such as gender that have a small number of options.

While this doesn't offer quite as much as having tags, it does allow you get data that is filtered easily via the API, as we provide methods to fetch the membership of a specific list.

Elijah Gaiter
API Support Engineer
Constant Contact
